name: Build and Publish LazyKeys
on:
  push:
    tags:
      - "v*"  # Trigger workflow on version tags (e.g., v1.0.0)
  workflow_dispatch:
    # Allow manual triggering of the workflow
    inputs:
      use_latest_tag:
        description: 'Use latest tag for release'
        required: true
        default: true
        type: boolean
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags
      
      # Set up Swift environment
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.7'
      
      # Get the version from Git
      - name: Get version from Git
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.use_latest_tag }}" == "true" ]]; then
            # For manual triggers, get the latest tag
            VERSION=$(git describe --tags --abbrev=0 || git rev-parse --short HEAD)
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            # For tag pushes, get the tag name
            VERSION=${GITHUB_REF#refs/tags/}
          else
            # Fallback
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version set to $VERSION"
      
      # Build the app using Make with the version passed as a compile-time variable
      - name: Build the app with Make
        run: |
          make VERSION="${{ env.VERSION }}" build
      
      # Create a tarball for the release
      - name: Create tarball
        run: |
          mkdir -p release
          tar -czf release/lazykeys.tar.gz -C bin lazykeys
          # Calculate SHA-256 for the formula
          SHA=$(shasum -a 256 release/lazykeys.tar.gz | awk '{print $1}')
          echo "SHA256=${SHA}" >> $GITHUB_ENV
      
      # Publish the release on GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Release version ${{ env.VERSION }}"
          files: release/lazykeys.tar.gz
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: false
          prerelease: false
      
      # Update Homebrew Formula (if it exists in the repo)
      - name: Update Homebrew Formula
        run: |
          FORMULA_PATH=Formula/lazykeys.rb
          if [ -f "$FORMULA_PATH" ]; then
            TAR_URL="https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/lazykeys.tar.gz"
            # Update the formula with the new version and URL
            sed -i '' "s|^  url .*|  url \"${TAR_URL}\"|" $FORMULA_PATH
            sed -i '' "s|^  sha256 .*|  sha256 \"${{ env.SHA256 }}\"|" $FORMULA_PATH
            
            # Configure Git
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            # Stage the changes
            git add $FORMULA_PATH
            
            # Only commit and push if there are changes
            if ! git diff --cached --quiet; then
              git commit -m "Update formula for version ${{ env.VERSION }}"
              git push origin HEAD:main
            else
              echo "No changes to commit."
            fi
          else
            echo "Formula file not found at $FORMULA_PATH. Skipping formula update."
          fi


      - name: Update lazykeys.nix
        run: |
          NIX_FILE=lazykeys.nix
          if [ -f "$NIX_FILE" ]; then
            # Update the version
            sed -i '' "s|^\s*version = \".*\";|  version = \"${{ env.VERSION }}\";|" $NIX_FILE
            
            # Update the URL
            sed -i '' "s|^\s*url = \".*\";|      url = \"https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/lazykeys.tar.gz\";|" $NIX_FILE
            
            # Update the SHA256
            sed -i '' "s|^\s*hash = \".*\";|      hash = \"sha256-${{ env.SHA256 }}\";|" $NIX_FILE
      
            # Configure Git
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
      
            # Stage the changes
            git add $NIX_FILE
            
            # Only commit if there are changes
            if ! git diff --cached --quiet; then
              git commit -m "Update lazykeys.nix for version ${{ env.VERSION }}"
              git push origin HEAD:main
            else
              echo "No changes to commit for lazykeys.nix."
            fi
          else
            echo "lazykeys.nix not found. Skipping update."
          fi
      
